apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sistema-noticia-state
spec:
  replicas: 1
  template:
    metadata:
      name: sistema-noticia
      labels:
        app: sistema-noticia
    spec:
      containers:
        - name: sistema-noticia-conteiner
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: sistema-config
          volumeMounts:
            - name: imagens
              mountPath: /var/www/html/uploads
            - name: sessao
              mountPath: /tmp
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /inserir_noticias.php
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
      volumes:
        - name: imagens
          persistentVolumeClaim:
            claimName: imagem-pvc
        - name: sessao
          persistentVolumeClaim:
            claimName: sessao-pvc
  selector:
    matchLabels:
      app: sistema-noticia
  serviceName: svc-sistema-noticia
      
