apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  template:
    metadata:
      name: db-deploy
      labels:
        app: db-deploy
    spec:
      containers:
        - name: nginx-container
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: db-config
  replicas: 1
  selector:
    matchLabels:
      app: db-deploy